In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.20.0'

In [4]:
dataset = pd.read_csv(r'C:\Users\kraja\OneDrive\Desktop\study material\3rd- Ensamble learning\7.XGBOOST\Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
dataset

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,delhi,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,delhi,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,delhi,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,mumbai,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,delhi,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
X

array([[619, 'delhi', 'Female', ..., 1, 1, 101348.88],
       [608, 'bangalore', 'Female', ..., 0, 1, 112542.58],
       [502, 'delhi', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 'Female', ..., 0, 1, 42085.58],
       [772, 'mumbai', 'Male', ..., 1, 0, 92888.52],
       [792, 'delhi', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [7]:
dataset.head(3)

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2 ]= le.fit_transform(X[:,2])

In [9]:
X

array([[619, 'delhi', 0, ..., 1, 1, 101348.88],
       [608, 'bangalore', 0, ..., 0, 1, 112542.58],
       [502, 'delhi', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 0, ..., 0, 1, 42085.58],
       [772, 'mumbai', 1, ..., 1, 0, 92888.52],
       [792, 'delhi', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [0.0 1.0 0.0 ... 1 0 113931.57]
 ...
 [0.0 1.0 0.0 ... 0 1 42085.58]
 [0.0 0.0 1.0 ... 1 0 92888.52]
 [0.0 1.0 0.0 ... 1 0 38190.78]]

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.74273971, -1.00280393, -0.57873591, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.57380915,  0.99720391, -0.57873591, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-0.57380915, -1.00280393,  1.72790383, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.57380915,  0.99720391, -0.57873591, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state =0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)

ANN MODEL BUILDING ARCHITECHTURE

In [14]:
ann = tf.keras.models.Sequential() # establish layer one after another

In [15]:
ann.add(tf.keras.layers.Dense(units=6))# input layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))## hidden layer1

In [17]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))# out put layer

In [18]:
ann.compile(optimizer='adam',loss ='binary_crossentropy',metrics=['accuracy'])

In [20]:
ann.fit(X_train,y_train,batch_size=32,epochs= 50)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8445 - loss: 0.3647
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.8474 - loss: 0.3634
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8465 - loss: 0.3620
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.8489 - loss: 0.3613
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.8489 - loss: 0.3596
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.8495 - loss: 0.3584
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8518 - loss: 0.3574
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8528 - loss: 0.3557
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8535 - loss: 0.3549
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.8534 - loss: 0.3535
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8549 - loss: 0.3526
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8555 - loss: 0.3514
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.8562 - loss: 0.3503
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.8570 - loss: 0.3498
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.8575 - loss: 0.3488
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.8587 - loss: 0.3486
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8585 - loss: 0.3478
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8596 - loss: 0.3471
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.8581 - loss: 0.3465
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8605 - loss: 0.3458
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8612 - loss: 0.3455
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.8597 - loss: 0.3445
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.8608 - loss: 0.3442
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8615 - loss: 0.3438
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8596 - loss: 0.3433
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.8609 - loss: 0.3429
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8596 - loss: 0.3427
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8601 - loss: 0.3423
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8609 - loss: 0.3421
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8595 - loss: 0.3421
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8610 - loss: 0.3415
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8602 - loss: 0.3415
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8619 - loss: 0.3414
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8620 - loss: 0.3412
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8605 - loss: 0.3409
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8621 - loss: 0.3408
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8614 - loss: 0.3404
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8619 - loss: 0.3401
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8610 - loss: 0.3404
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3401
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8614 - loss: 0.3402
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8615 - loss: 0.3398
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8621 - loss: 0.3400
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8610 - loss: 0.3395
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8641 - loss: 0.3398
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8615 - loss: 0.3396
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8620 - loss: 0.3397
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8609 - loss: 0.3396
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8627 - loss: 0.3393
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8612 - loss: 0.3396